extend type Query {
  books: [Book!]
}

type Book {
  id: Int!
  title: String!
  author: String
}

input BookAdd {
  title: String!
  author: String
}

extend type Mutation {
  bookAdd(input: [BookAdd!]!): [Book!]
}
