extend type Query {
  books(
    input: [BookInput!]
    order: [BookOrder!]
    pagination: PaginationInput
  ): BooksConnection
}

type pageInfo {
  page: Int!
  allPage: Int!
  scale: Int!
}

type Book {
  bookId: Int!
  title: String!
  author: String
}

type BooksConnection {
  _pageInfo: pageInfo!
  books: [Book!]!
}

input BookInput {
  bookId: WhereInt
  title: WhereString
  author: WhereString
}

input BookOrder {
  type: BookType!
  order: Order!
}

enum BookType {
  bookId
  title
  author
}

extend type Mutation {
  bookAdd(input: [BookAdd!]!): [Book!]
}

input BookAdd {
  title: String!
  author: String
}
